### PR TITLE
 Center images in page layout

### PR DESCRIPTION
**Pull request by MukeshOdhano**
# Issue_No:- #33 

Added CSS styles to center images horizontally and vertically within their container

### CODE REVIEW

**Comment by priyankarpal** [comment]
Could you add a good title, description & issue number?

**Comment by MukeshOdhano** [comment]
> Could you add a good title, description & issue number?

How does it look now?

**Comment by priyankarpal** [comment]
> > Could you add a good title, description & issue number?
> 
> How does it look now?

Now it's ok

**Comment by priyankarpal** [comment]
ok, you have used `npm` to install dependencies. We use `pnpm` instead of `npm` to create a new PR. 

Install dependencies by `pnpm i`
Run dependencies using `pnpm dev`

**Comment by MukeshOdhano** [comment]
> pnpm i

do i have to install pnpm

**Comment by priyankarpal** [comment]
> > pnpm i
> 
> do i have to install pnpm

yes

**Pull request closed without merging**
