### PR TITLE
CONTRIBUTING.md is made comprehensive

### PR DESCRIPTION
**Pull request by me-imfhd**
I updated the contributing file.... made a step by guide to how to make contribution even for the one who has prior no experience in git and github.
Maintainers please add somewhere that any beginner need not to worry and can read this  CONTRIBUTING>md file and start to contribute right away, even if he also do not know anything about git and github.

### CODE REVIEW

**Comment by me-imfhd** [comment]
@priyankarpal please review it.... can you merge this... or need something extra?

**Comment by priyankarpal** [comment]
could you share a screenshot?

**Comment by me-imfhd** [comment]
> could you share a screenshot?

you can check it from my contributing.md file in my repository , here : https://github.com/me-imfhd/Code-Nexus/blob/main/CONTRIBUTING.md

**Comment by me-imfhd** [comment]
> Looks Good 🎉

Thank you very much....this is my first contribution.

**Pull request merged**
